import { ClothingItem } from '@/types/clothing';

/**
 * Mock clothing database with sample items covering various scenarios
 * In a real application, this would be replaced with actual API calls or database queries
 */

export const MOCK_CLOTHING_ITEMS: ClothingItem[] = [
  // Cold Weather (< 10°C) - Western
  {
    id: 'w_cold_1',
    type: 'outerwear',
    name: 'Black Wool Overcoat',
    imageUrl: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400',
    color: 'black',
    material: 'wool',
    culture: 'western',
    style: 'unisex',
    dressCode: 'formal',
    temperatureRange: { min: -10, max: 10 },
    buyLink: 'https://example.com/black-wool-coat',
  },
  {
    id: 'w_cold_2',
    type: 'top',
    name: 'Cashmere Turtleneck Sweater',
    imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400',
    color: 'navy',
    material: 'cashmere',
    culture: 'western',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: -5, max: 12 },
    buyLink: 'https://example.com/cashmere-sweater',
  },
  {
    id: 'w_cold_3',
    type: 'bottom',
    name: 'Dark Denim Jeans',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
    color: 'blue',
    material: 'denim',
    culture: 'western',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: -10, max: 20 },
    buyLink: 'https://example.com/dark-jeans',
  },
  {
    id: 'w_cold_4',
    type: 'shoes',
    name: 'Leather Ankle Boots',
    imageUrl: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=400',
    color: 'brown',
    material: 'leather',
    culture: 'western',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: -10, max: 15 },
    buyLink: 'https://example.com/leather-boots',
  },

  // Moderate Weather (10-20°C) - Western
  {
    id: 'w_mod_1',
    type: 'top',
    name: 'Oxford Button-Down Shirt',
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400',
    color: 'white',
    material: 'cotton',
    culture: 'western',
    style: 'masculine',
    dressCode: 'semi-formal',
    temperatureRange: { min: 10, max: 22 },
    buyLink: 'https://example.com/oxford-shirt',
  },
  {
    id: 'w_mod_2',
    type: 'bottom',
    name: 'Chino Trousers',
    imageUrl: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400',
    color: 'beige',
    material: 'cotton',
    culture: 'western',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: 12, max: 25 },
    buyLink: 'https://example.com/chino-pants',
  },
  {
    id: 'w_mod_3',
    type: 'shoes',
    name: 'White Sneakers',
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400',
    color: 'white',
    material: 'leather',
    culture: 'western',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: 5, max: 30 },
    buyLink: 'https://example.com/white-sneakers',
  },

  // Warm Weather (20-30°C) - Western
  {
    id: 'w_warm_1',
    type: 'top',
    name: 'Linen Short-Sleeve Shirt',
    imageUrl: 'https://images.unsplash.com/photo-1602810318660-d0c8afaa0408?w=400',
    color: 'beige',
    material: 'linen',
    culture: 'western',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: 20, max: 35 },
    buyLink: 'https://example.com/linen-shirt',
  },
  {
    id: 'w_warm_2',
    type: 'bottom',
    name: 'Cotton Shorts',
    imageUrl: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400',
    color: 'navy',
    material: 'cotton',
    culture: 'western',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: 22, max: 40 },
    buyLink: 'https://example.com/cotton-shorts',
  },
  {
    id: 'w_warm_3',
    type: 'shoes',
    name: 'Canvas Slip-Ons',
    imageUrl: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400',
    color: 'gray',
    material: 'cotton',
    culture: 'western',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: 15, max: 35 },
    buyLink: 'https://example.com/canvas-shoes',
  },

  // African Traditional - Moderate
  {
    id: 'a_mod_1',
    type: 'top',
    name: 'Dashiki Shirt',
    imageUrl: 'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=400',
    color: 'multicolor',
    material: 'cotton',
    culture: 'african',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: 15, max: 30 },
    buyLink: 'https://example.com/dashiki',
  },
  {
    id: 'a_mod_2',
    type: 'bottom',
    name: 'African Print Trousers',
    imageUrl: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400',
    color: 'multicolor',
    material: 'cotton',
    culture: 'african',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: 18, max: 32 },
    buyLink: 'https://example.com/african-trousers',
  },
  {
    id: 'a_warm_1',
    type: 'top',
    name: 'Boubou',
    imageUrl: 'https://images.unsplash.com/photo-1600091234997-fc2e8de5d8a7?w=400',
    color: 'white',
    material: 'cotton',
    culture: 'african',
    style: 'gender-fluid',
    dressCode: 'formal',
    temperatureRange: { min: 20, max: 38 },
    buyLink: 'https://example.com/boubou',
  },

  // Indian Traditional
  {
    id: 'i_warm_1',
    type: 'top',
    name: 'Kurta',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400',
    color: 'white',
    material: 'cotton',
    culture: 'indian',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: 18, max: 35 },
    buyLink: 'https://example.com/kurta',
  },
  {
    id: 'i_cold_1',
    type: 'outerwear',
    name: 'Wool Shawl',
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400',
    color: 'red',
    material: 'wool',
    culture: 'indian',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: -5, max: 15 },
    buyLink: 'https://example.com/wool-shawl',
  },
  {
    id: 'i_mod_1',
    type: 'top',
    name: 'Silk Kurta',
    imageUrl: 'https://images.unsplash.com/photo-1583391733981-f8c36ab78e56?w=400',
    color: 'blue',
    material: 'silk',
    culture: 'indian',
    style: 'feminine',
    dressCode: 'formal',
    temperatureRange: { min: 15, max: 28 },
    buyLink: 'https://example.com/silk-kurta',
  },

  // Formal Western
  {
    id: 'w_formal_1',
    type: 'top',
    name: 'Tailored Blazer',
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400',
    color: 'navy',
    material: 'wool',
    culture: 'western',
    style: 'masculine',
    dressCode: 'formal',
    temperatureRange: { min: 10, max: 22 },
    buyLink: 'https://example.com/blazer',
  },
  {
    id: 'w_formal_2',
    type: 'bottom',
    name: 'Dress Trousers',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400',
    color: 'gray',
    material: 'wool',
    culture: 'western',
    style: 'unisex',
    dressCode: 'formal',
    temperatureRange: { min: 10, max: 25 },
    buyLink: 'https://example.com/dress-pants',
  },
  {
    id: 'w_formal_3',
    type: 'shoes',
    name: 'Oxford Dress Shoes',
    imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400',
    color: 'black',
    material: 'leather',
    culture: 'western',
    style: 'masculine',
    dressCode: 'formal',
    temperatureRange: { min: 5, max: 30 },
    buyLink: 'https://example.com/oxford-shoes',
  },

  // Feminine Styles
  {
    id: 'w_fem_1',
    type: 'top',
    name: 'Silk Blouse',
    imageUrl: 'https://images.unsplash.com/photo-1564257577-4325c0e28c33?w=400',
    color: 'pink',
    material: 'silk',
    culture: 'western',
    style: 'feminine',
    dressCode: 'semi-formal',
    temperatureRange: { min: 15, max: 28 },
    buyLink: 'https://example.com/silk-blouse',
  },
  {
    id: 'w_fem_2',
    type: 'bottom',
    name: 'A-Line Skirt',
    imageUrl: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=400',
    color: 'black',
    material: 'polyester',
    culture: 'western',
    style: 'feminine',
    dressCode: 'casual',
    temperatureRange: { min: 15, max: 30 },
    buyLink: 'https://example.com/a-line-skirt',
  },
  {
    id: 'w_fem_3',
    type: 'shoes',
    name: 'Heeled Boots',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400',
    color: 'brown',
    material: 'leather',
    culture: 'western',
    style: 'feminine',
    dressCode: 'casual',
    temperatureRange: { min: 5, max: 20 },
    buyLink: 'https://example.com/heeled-boots',
  },

  // East Asian
  {
    id: 'ea_mod_1',
    type: 'top',
    name: 'Mandarin Collar Shirt',
    imageUrl: 'https://images.unsplash.com/photo-1598032895397-b9372c935f8b?w=400',
    color: 'white',
    material: 'cotton',
    culture: 'east-asian',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: 15, max: 28 },
    buyLink: 'https://example.com/mandarin-shirt',
  },
  {
    id: 'ea_formal_1',
    type: 'top',
    name: 'Silk Hanfu',
    imageUrl: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=400',
    color: 'red',
    material: 'silk',
    culture: 'east-asian',
    style: 'gender-fluid',
    dressCode: 'formal',
    temperatureRange: { min: 12, max: 25 },
    buyLink: 'https://example.com/hanfu',
  },

  // Middle Eastern
  {
    id: 'me_warm_1',
    type: 'top',
    name: 'Thobe',
    imageUrl: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400',
    color: 'white',
    material: 'cotton',
    culture: 'middle-eastern',
    style: 'masculine',
    dressCode: 'casual',
    temperatureRange: { min: 20, max: 45 },
    buyLink: 'https://example.com/thobe',
  },
  {
    id: 'me_mod_1',
    type: 'top',
    name: 'Embroidered Kaftan',
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400',
    color: 'blue',
    material: 'silk',
    culture: 'middle-eastern',
    style: 'feminine',
    dressCode: 'semi-formal',
    temperatureRange: { min: 18, max: 32 },
    buyLink: 'https://example.com/kaftan',
  },

  // Accessories
  {
    id: 'acc_cold_1',
    type: 'accessory',
    name: 'Wool Scarf',
    imageUrl: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400',
    color: 'gray',
    material: 'wool',
    culture: 'western',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: -10, max: 10 },
    buyLink: 'https://example.com/wool-scarf',
  },
  {
    id: 'acc_warm_1',
    type: 'accessory',
    name: 'Sun Hat',
    imageUrl: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400',
    color: 'beige',
    material: 'cotton',
    culture: 'western',
    style: 'unisex',
    dressCode: 'casual',
    temperatureRange: { min: 20, max: 40 },
    buyLink: 'https://example.com/sun-hat',
  },

  // Androgynous Styles
  {
    id: 'w_andro_1',
    type: 'top',
    name: 'Oversized Button-Up',
    imageUrl: 'https://images.unsplash.com/photo-1598522325074-042db73aa4e6?w=400',
    color: 'white',
    material: 'cotton',
    culture: 'western',
    style: 'androgynous',
    dressCode: 'casual',
    temperatureRange: { min: 15, max: 28 },
    buyLink: 'https://example.com/oversized-shirt',
  },
  {
    id: 'w_andro_2',
    type: 'bottom',
    name: 'Wide-Leg Trousers',
    imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400',
    color: 'black',
    material: 'polyester',
    culture: 'western',
    style: 'androgynous',
    dressCode: 'semi-formal',
    temperatureRange: { min: 12, max: 28 },
    buyLink: 'https://example.com/wide-leg-pants',
  },
];

/**
 * Get all clothing items
 */
export const getAllClothingItems = (): ClothingItem[] => {
  return [...MOCK_CLOTHING_ITEMS];
};

/**
 * Get clothing item by ID
 */
export const getClothingItemById = (id: string): ClothingItem | undefined => {
  return MOCK_CLOTHING_ITEMS.find(item => item.id === id);
};

/**
 * Get clothing items by type
 */
export const getClothingItemsByType = (type: ClothingItem['type']): ClothingItem[] => {
  return MOCK_CLOTHING_ITEMS.filter(item => item.type === type);
};

